import Header from "@/components/marketing/Header";
import Footer from "@/components/marketing/Footer";

export default function TermsPage() {
  return (
    <main className="min-h-screen">
      <Header />
      <div className="pt-32 pb-20 px-6 max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>

        <div className="prose prose-neutral max-w-none space-y-6 text-foreground/80 leading-relaxed">
          <p>Last updated: March 2026</p>

          <h2 className="text-xl font-semibold text-foreground mt-8">1. Acceptance of Terms</h2>
          <p>By accessing or using ReviewReply, you agree to be bound by these Terms of Service. If you do not agree, do not use the service.</p>

          <h2 className="text-xl font-semibold text-foreground mt-8">2. Description of Service</h2>
          <p>ReviewReply provides an AI-powered tool that helps restaurant owners analyze customer reviews and generate professional responses. The service includes sentiment analysis, response generation, trends analysis, and competitor analysis.</p>

          <h2 className="text-xl font-semibold text-foreground mt-8">3. User Accounts</h2>
          <p>You must provide accurate information when creating an account. You are responsible for maintaining the security of your account and for all activities that occur under it.</p>

          <h2 className="text-xl font-semibold text-foreground mt-8">4. Subscription & Billing</h2>
          <p>Paid plans are billed monthly. You can cancel at any time, and your subscription will remain active until the end of the current billing period. Refunds are handled on a case-by-case basis.</p>

          <h2 className="text-xl font-semibold text-foreground mt-8">5. AI-Generated Content</h2>
          <p>Responses generated by our AI are suggestions. You are responsible for reviewing and editing them before publishing. ReviewReply is not liable for any consequences of publishing AI-generated responses.</p>

          <h2 className="text-xl font-semibold text-foreground mt-8">6. Intellectual Property</h2>
          <p>You retain ownership of all content you provide. We retain ownership of the ReviewReply platform, algorithms, and branding. AI-generated responses are licensed to you for use.</p>

          <h2 className="text-xl font-semibold text-foreground mt-8">7. Limitation of Liability</h2>
          <p>ReviewReply is provided &quot;as is&quot; without warranties. We are not liable for indirect, incidental, or consequential damages arising from your use of the service.</p>

          <h2 className="text-xl font-semibold text-foreground mt-8">8. Changes to Terms</h2>
          <p>We may update these terms from time to time. We will notify you of significant changes via email or through the platform.</p>

          <h2 className="text-xl font-semibold text-foreground mt-8">9. Contact</h2>
          <p>For questions about these terms, please contact us at legal@reviewreply.ai.</p>
        </div>
      </div>
      <Footer />
    </main>
  );
}
